version: '3.8'
services:
  grpc-server:
    build: ./server
    ports:
      - "50051:50051"
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: grpc_user
      MYSQL_PASSWORD: grpc_password
      MYSQL_DATABASE: grpc_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
